apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: my-mysql-operator
    meta.helm.sh/release-namespace: mysql-operator
  creationTimestamp: "2023-04-27T18:11:25Z"
  generation: 1
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: my-mysql-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/version: 8.0.33-2.0.9
    version: 8.0.33-2.0.9
  name: mysql-operator
  namespace: mysql-operator
  resourceVersion: "8872"
  uid: d2725dab-3395-40ee-950d-c19149a1d9b2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: mysql-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql-operator
    spec:
      containers:
      - args:
        - mysqlsh
        - --log-level=@INFO
        - --pym
        - mysqloperator
        - operator
        env:
        - name: MYSQLSH_USER_CONFIG_HOME
          value: /mysqlsh
        - name: MYSQLSH_CREDENTIAL_STORE_SAVE_PASSWORDS
          value: never
        - name: MYSQL_OPERATOR_IMAGE_PULL_POLICY
          value: IfNotPresent
        image: container-registry.oracle.com/mysql/community-operator:8.0.33-2.0.9
        imagePullPolicy: IfNotPresent
        name: mysql-operator
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/mysql-operator-ready
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mysqlsh
          name: mysqlsh-home
        - mountPath: /tmp
          name: tmpdir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mysql-operator-sa
      serviceAccountName: mysql-operator-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: mysqlsh-home
      - emptyDir: {}
        name: tmpdir
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-27T18:11:36Z"
    lastUpdateTime: "2023-04-27T18:11:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-27T18:11:25Z"
    lastUpdateTime: "2023-04-27T18:11:36Z"
    message: ReplicaSet "mysql-operator-778db9855c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
